from __future__ import annotations

from pathlib import Path

from .providers import HistoricalBar


def render_chart_widget(symbol: str, bars: list[HistoricalBar], dashboard_dir: Path) -> Path | None:
    points = [(bar.date, bar.close) for bar in bars if bar.close is not None]
    if len(points) < 2:
        return None

    dashboard_dir.mkdir(parents=True, exist_ok=True)
    path = dashboard_dir / f"{symbol.lower()}_chart.html"
    svg = _line_chart_svg(points)
    latest_date, latest_close = points[-1]

    path.write_text(
        f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{symbol} Stock Chart</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 24px; color: #111827; }}
    .card {{ max-width: 780px; border: 1px solid #e5e7eb; border-radius: 16px; padding: 20px; box-shadow: 0 8px 24px #0001; }}
    .muted {{ color: #6b7280; }}
  </style>
</head>
<body>
  <div class="card">
    <h1>{symbol} Stock Chart</h1>
    <p class="muted">Latest close: ${latest_close:,.2f} on {latest_date}</p>
    {svg}
    <p class="muted">Generated by the OpenClaw stock agent. Informational only.</p>
  </div>
</body>
</html>
""",
        encoding="utf-8",
    )
    return path


def _line_chart_svg(points: list[tuple[str, float]]) -> str:
    width = 720
    height = 280
    padding = 36
    closes = [close for _, close in points]
    low = min(closes)
    high = max(closes)
    span = high - low or 1

    coords = []
    for idx, (_, close) in enumerate(points):
        x = padding + (idx / (len(points) - 1)) * (width - padding * 2)
        y = height - padding - ((close - low) / span) * (height - padding * 2)
        coords.append(f"{x:.1f},{y:.1f}")

    return f"""<svg viewBox="0 0 {width} {height}" role="img" aria-label="Stock price line chart">
  <rect x="0" y="0" width="{width}" height="{height}" fill="#f9fafb" rx="12" />
  <line x1="{padding}" y1="{height - padding}" x2="{width - padding}" y2="{height - padding}" stroke="#d1d5db" />
  <line x1="{padding}" y1="{padding}" x2="{padding}" y2="{height - padding}" stroke="#d1d5db" />
  <polyline points="{' '.join(coords)}" fill="none" stroke="#2563eb" stroke-width="3" />
  <text x="{padding}" y="24" fill="#6b7280" font-size="12">${high:,.2f}</text>
  <text x="{padding}" y="{height - 8}" fill="#6b7280" font-size="12">${low:,.2f}</text>
</svg>"""
